# 차원 미니퀘스트

*   .ndim: 차원 수
*   .shape: 배열 모양 확인
* reshape: 형태 변경


In [ ]:
# 01. 다음 NumPy 배열의 차원 수를 출력하는 코드를 작성하세요.

import numpy as np
array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(array.ndim) # ndim: 차원의 수 출력

3


In [ ]:
# 02. 1차원 배열 [10, 20, 30, 40, 50, 60]을 2차원 배열로 변환하여 (2, 3) 형태로 출력하는 코드를 작성하세요.

import numpy as np
array = np.array([10, 20, 30, 40, 50, 60])
reshaped = array.reshape(2, 3)  # reshape로 2차원 배열로 전환

print(reshaped)

[[10 20 30]
 [40 50 60]]


In [ ]:
# 03. 다음 1차원 배열에 새로운 차원을 추가하여 2차원 배열로 변환하고, 최종 배열의 차원 수를 출력하세요.
# newaxis를 사용하여 배열의 차원을 추가하고, 새로운 차원에서의 배열 모양을 확인한 후 최종 차원 수를 출력하세요.

import numpy as np
array = np.array([7, 14, 21])

new_array = array[np.newaxis, :]  # np.newaxis: 새로운 차원 추가

print(new_array)  # 배열 출력
print(new_array.shape)  # 배열 모양 확인
print(new_array.ndim) # 차원 수

[[ 7 14 21]]
(1, 3)
2


# Shape 미니퀘스트

In [ ]:
# 01. 주어진 2차원 NumPy 배열의 형태(Shape)를 출력하는 코드를 작성하세요.

import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])

print(array.shape)

(2, 3)


In [ ]:
# 02. 1차원 배열 [10, 20, 30, 40, 50, 60]을 (2, 3) 형태로 변경한 후, 새로운 배열의 형태를 출력하는 코드를 작성하세요.

import numpy as np
array = np.array([10, 20, 30, 40, 50, 60])
reshaped = array.reshape(2, 3)

print(reshaped.shape)

(2, 3)


In [ ]:
# 03. 다음 1차원 배열의 형태를 변경하여 (3, 2, 2) 형태로 조정하고, 최종 배열의 형태를 출력하는 코드를 작성하세요.

import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

reshaped = array.reshape(3, 2, 2)

print(reshaped)
print(reshaped.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)


# 데이터 타입 미니퀘스트
* .dtype: 배열의 데이터 타입 확인
* .astype(float)으로 정수형 → 부동소수점형으로 변환
* .nbytes: 메모리 사용량 출력

In [ ]:
# 01. 아래의 NumPy 배열의 데이터 타입을 확인하는 코드를 작성하세요.

import numpy as np
array = np.array([10, 20, 30])

print(array.dtype)  # .dtype: 배열의 데이터 타입 확인

int64


In [ ]:
# 02. 정수형 배열 [1, 2, 3]을 부동소수점형 배열로 변환하고, 변환된 배열의 데이터 타입을 출력하는 코드를 작성하세요.

import numpy as np
array = np.array([1, 2, 3])
float_array = array.astype(float) # .astype(float)으로 정수형 → 부동소수점형으로 변환

print(float_array)
print(float_array.dtype)


[1. 2. 3.]
float64


In [ ]:
# 03. NumPy 배열 [100, 200, 300]을 uint8로 변환한 후, 메모리 사용량(바이트)을 출력하는 코드를 작성하세요.

import numpy as np
array = np.array([100, 200, 300])
uint8_array = array.astype(np.uint8)

print(uint8_array)
print(uint8_array.dtype)
print(uint8_array.nbytes)  # .nbytes: 메모리 사용량 출력

[100 200  44]
uint8
3


# 인덱싱 미니퀘스트

In [ ]:
# 01. 주어진 1차원 배열에서 첫 번째 요소와 마지막 요소를 출력하는 코드를 작성하세요.

import numpy as np
array = np.array([10, 20, 30, 40, 50])

print(array[0]) # 첫 번째 요소
print(array[-1])  # 마지막 요소

10
50


In [ ]:
# 02. 주어진 2차원 배열에서 첫 번째 열과 두 번째 행을 출력하는 코드를 작성하세요.

import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix[:, 0])  # 첫 번째 열 출력
print(matrix[1])  # print(matrix[1, :]) 이렇게 적어도 결과는 같음

[1 4 7]
[4 5 6]


In [ ]:
# 03. 주어진 배열에서 10보다 큰 요소들만 선택하고, 해당 요소들의 인덱스를 출력하는 코드를 작성하세요.

import numpy as np
array = np.array([5, 15, 8, 20, 3, 12])

mask = array > 10
print(array[mask])           # 10보다 큰 요소들
print(np.where(mask)[0])     # 해당 요소들의 인덱스

[15 20 12]
[1 3 5]


# 연산 미니퀘스트

In [ ]:
# 01. 주어진 NumPy 배열에서 요소별(Element-wise) 덧셈을 수행하는 코드를 작성하세요.

import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

[5 7 9]


In [ ]:
# 02. 다음 NumPy 배열에서 브로드캐스팅을 활용하여 각 행에 [1, 2, 3]을 더하는 코드를 작성하세요.
# 브로드캐스팅: shape이 다른 배열끼리 연산할 때 작은 배열을 자동으로 늘려서 계산하는 기능

import numpy as np
matrix = np.array([[10, 20, 30], [40, 50, 60]])
vector = np.array([1, 2, 3])

print(matrix + vector)

[[11 22 33]
 [41 52 63]]


In [ ]:
# 03. 주어진 2차원 NumPy 배열에 대해, 축(axis)을 기준으로 최댓값을 구하고 최종 배열의 차원을 출력하는 코드를 작성하세요.

import numpy as np
array = np.array([[3, 7, 2], [8, 4, 6]])

max_axis0 = np.max(array, axis=0)  # 열 기준 최댓값
max_axis1 = np.max(array, axis=1)  # 행 기준 최댓값

print(max_axis0)        # 열 기준 최댓값
print(max_axis0.ndim)   # 차원 수

print(max_axis1)        # 행 기준 최댓값
print(max_axis1.ndim)   # 차원 수

[8 7 6]
1
[7 8]
1


# 유니버셜함수 미니퀘스트


*   **np.square()**: 배열의 모든 요소를 한 번에 **제곱**
*   **np.add()의 out** 파라미터: 새로운 배열을 생성하지 않고 **기존 배열에 결과를 저장**



In [ ]:
# 01. 배열 [1, 2, 3, 4]에 대해 NumPy의 유니버설 함수를 사용하여 모든 요소를 제곱한 결과를 출력하는 코드를 작성하세요.

import numpy as np
array = np.array([1, 2, 3, 4])
result = np.square(array) # np.square(): 배열의 모든 요소를 한 번에 제곱

print(result)


[ 1  4  9 16]


In [ ]:
# 02. 다음 두 배열의 요소별 합을 계산하고, 결과를 새로운 배열이 아닌 기존 배열에 저장하는 코드를 작성하세요.

array1 = np.array([10, 20, 30])
array2 = np.array([1, 2, 3])

np.add(array1, array2, out=array1)  # 결과를 array1에 저장

print(array1)

[11 22 33]


### 메모리 동작 방식 비교

`array1 = array1 + array2` 방식
- array1 → [10, 20, 30]  (기존 메모리)
- result → [11, 22, 33]  (새 메모리 생성)
- array1 → [11, 22, 33]  (array1이 새 메모리를 가리킴)
- ❌ 메모리를 **2개** 사용 (잠깐이라도)

`out=array1` 방식
- array1 → [10, 20, 30]  (기존 메모리)
- array1 → [11, 22, 33]  (같은 메모리에 덮어씀)
- ✅ 메모리를 **1개**만 사용

In [ ]:
# 03. 다음 배열에 대해 NumPy 유니버설 함수를 사용하여 요소별로 자연로그(log)를 계산하고,
# 특정 조건(log 값 > 1)을 만족하는 요소만 출력하는 코드를 작성하세요.

import numpy as np
array = np.array([1, np.e, 10, 100])

log_array = np.log(array) # 자연로그 계산
print(log_array)

mask = log_array > 1  # boolean 개념을 통상적으로 mask라고 많이 표현함
print(array[mask])  # 조건 만족하는 원소 출력

[0.         1.         2.30258509 4.60517019]
[ 10. 100.]
